# Generated by Django 2.2.5 on 2019-09-13 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='quote',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='dailystockprice',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockTimeStamp', to_field='date'),
        ),
        migrations.AlterField(
            model_name='dailystockprice',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Company', to_field='quote'),
        ),
        migrations.AlterField(
            model_name='stocktimestamp',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
