---
apiVersion: v1
kind: Namespace
metadata:
  name: btools

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: btools-pvc
  namespace: btools
  labels:
    env: development
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Secret
metadata:
  namespace: btools
  name: postgres-secret
type: Opaque
data:
  admin_password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: btools
  name: postgres-config
data:
  POSTGRES_DB: btools
  POSTGRES_USER: telescreen

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: btools
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        env: development
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: admin_password
          envFrom:
          - configMapRef:
              name: postgres-config
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: btools-pvc

---
apiVersion: v1
kind: Service
metadata:
  namespace: btools
  name: postgres
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
