# Generated by Django 2.2.5 on 2019-09-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20190909_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
